### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by seb-thomas** [mattstauffer/syncCraft#1]
Hiya, thanks very much for the plugin - looks good! 

I'm having trouble with the zips. If I unzip the downloaded `craftAssetDownload_Uploads_1440175336.zip` with OSX default Archive Utility it unzips a file `craftAssetDownload_Uploads_1440175336.zip.cpgz`, and if I unzip that it contains another zip! And so on. 

If I try to use Keka or another zip program, it get parse errors, or unable to 'determine the format of the file'. 
I'm going to try and move to your other Sync plugin soon anyway, but it might be useful to fix this (if it is in fact a problem with the plugin)

Oh and the zip is 0 bytes. 

thanks

**Comment by mattstauffer** [comment]
Hm. I haven't run this for a while, but I don't remember anything about zip files. Are you sure that's a file that was created by this package?

**Comment by seb-thomas** [comment]
...what the heck. Sorry, have been too tired lately!! This issue was of course meant for your other plugin: 
https://github.com/mattstauffer/craftcms-DownloadAssets
